name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Haha-lol
       uses: ./.github/actions/joke-action
